steps:

- name: 'gcr.io/cloud-builders/npm'
  args: [ 'install' ]

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Deploying and building branch $BRANCH_NAME @ $REPO_NAME... "
    case $BRANCH_NAME in
      master)
        mv app.prod.yaml app.yaml
        mv .env.template .env
        sed -i 's|__INSTHOME__|TESTTTTT|g' .env
        ;;
      develop)
        mv app.dev.yaml app.yaml
        mv .env.template .env
        sed -i 's|__INSTHOME__|TESTTTTTDEV|g' .env
        ;;
      *)
        echo "branch $BRANCH_NAME ignored."
    esac


- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project', '$PROJECT_ID', '-v', 'nac']
substitutions:
    _ENVIRONMENT: world
    REPO_NAME: reponamenih
    COMMIT_SHA: comitsha
options:
    substitution_option: 'ALLOW_LOOSE'