steps:

- name: 'gcr.io/cloud-builders/npm'
  args: [ 'install' ]

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Deploying and building branch $BRANCH_NAME @ $REPO_NAME... "
    case $BRANCH_NAME in
      master)
        gcloud builds submit --config=config.yaml --substitutions=_ENVIRONMENT="production",REPO_NAME="$REPO_NAME",COMMIT_SHA="$COMMIT_SHA"
        ;;
      dev)
        gcloud builds submit --config=config.yaml --substitutions=_ENVIRONMENT="staging",REPO_NAME="$REPO_NAME",COMMIT_SHA="$COMMIT_SHA"
        ;;
      *)
        echo "branch $BRANCH_NAME ignored."
    esac


- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project', '$PROJECT_ID', '-v', 'nac']
substitutions:
    _ENVIRONMENT: world
    REPO_NAME: reponamenih
    COMMIT_SHA: comitsha
options:
    substitution_option: 'ALLOW_LOOSE'